[global]
template_dir = "templates/"

# Option 1:
[default.databases.sqlite_database]
url = "database/db.sqlite"

[default.databases]
persons = { url = "postgres://postgres:1922leon@localhost/persons" }

[development]
address = "localhost"
port = 8000
workers = 2
keep_alive = 5
log = "normal"
# secret_key = [randomly generated at launch]