[global]
template_dir = "templates/"

[default.databases]
persons = { url = "postgres://postgres:password@localhost/persons" }

[development]
address = "localhost"
port = 8000
workers = 2
keep_alive = 5
log = "normal"
# secret_key = [randomly generated at launch]
